### PR TITLE
[TIMOB-20547] Add keychain-access to Ti.TouchID, add passcode-policy, add more TouchID API's

### PR DESCRIPTION
**Pull request by hansemannn**
JIRA: https://jira.appcelerator.org/browse/TIMOB-20547

### CODE REVIEW

**Comment by collinprice** [comment]
I am curious why you didn't use `SecAccessControl` to increase the security of TouchId. Using SecAccessControl would enable you to automatically remove key/value pairs that have been saved when a new fingerprint is added/removed. Maybe this could be a flag during the save method?

```
SecAccessControlRef sacObject = SecAccessControlCreateWithFlags(kCFAllocatorDefault,
                                                                    kSecAttrAccessibleWhenPasscodeSetThisDeviceOnly,
                                                                    kSecAccessControlTouchIDCurrentSet, &error);

query[(__bridge id)kSecAttrAccessControl] = (__bridge_transfer id)sacObject;
```

**Comment by hansemannn** [comment]
Hey @collinprice, thanks for the feedback! Just updated the PR with a configurable access-control and exposed these `accessibilityMode` constants:

```js
ACCESSIBLE_WHEN_UNLOCKED
ACCESSIBLE_AFTER_FIRST_UNLOCK
ACCESSIBLE_ALWAYS
ACCESSIBLE_WHEN_PASSCODE_SET_THIS_DEVICE_ONLY
ACCESSIBLE_WHEN_UNLOCKED_THIS_DEVICE_ONLY
ACCESSIBLE_AFTER_FIRST_UNLOCK_THIS_DEVICE_ONLY
ACCESSIBLE_ALWAYS_THIS_DEVICE_ONLY
```

The second flag (`SecAccessControlCreateFlags`) is not exposed, yet and set to `kSecAccessControlUserPresence` for now (which matches Apple's default behavior). Would it make sense to expose all of those constants as `accessControlMode` well? It's more an advanced configuration, so I would like to keep this for the default behavior if nothing else is set. The following constants would make sense to be exposed:

```objc
kSecAccessControlUserPresence           = 1 << 0,                                 // User presence policy using Touch ID or Passcode. Touch ID does not have to be available or enrolled. Item is still accessible by Touch ID even if fingers are added or removed.
kSecAccessControlTouchIDAny             CF_ENUM_AVAILABLE(NA, 9_0)    = 1u << 1,   // Constraint: Touch ID (any finger). Touch ID must be available and at least one finger must be enrolled. Item is still accessible by Touch ID even if fingers are added or removed.
kSecAccessControlTouchIDCurrentSet      CF_ENUM_AVAILABLE(NA, 9_0)    = 1u << 3,   // Constraint: Touch ID from the set of currently enrolled fingers. Touch ID must be available and at least one finger must be enrolled. When fingers are added or removed, the item is invalidated.
kSecAccessControlDevicePasscode         CF_ENUM_AVAILABLE(10_11, 9_0) = 1u << 4,   // Constraint: Device passcode
```

Hans

**Comment by hansemannn** [comment]
Ok, exposed the `kSecAccessControl***` flags as the `accessControlMode` property as well. Properties (can be concatenated by a logical AND):

```js
ACCESS_CONTROL_USER_PRESENCE
ACCESS_CONTROL_TOUCH_ID_ANY
ACCESS_CONTROL_TOUCH_ID_CURRENT_SET
ACCESS_CONTROL_DEVICE_PASSCODE
ACCESS_CONTROL_OR
ACCESS_CONTROL_AND
ACCESS_CONTROL_PRIVATE_KEY_USAGE
ACCESS_CONTROL_APPLICATION_PASSWORD
```

Note: You need to set the `accessibilityMode` property in order to use this ones.

Finally, I also found two iOS9 properties for the TouchID dialog (`maxBiometryFailures` and `allowableReuseDuration`) which are quite self-describing I guess. So as soon as you approve the PR, I will do the public documentation and let it review by our team as well. Thanks!

Hans

**Comment by hansemannn** [comment]
Hey @collinprice, I found one open issue with the way we save the values. It is recommended to save the values as data (`NSData`), read them back and encode them as a strings (`NSString`). I can successfully save them but will need a bit more time on receiving them back. Can you already approve the API/interface structure so I can write-up the docs? Thanks man!

**Comment by collinprice** [comment]
@hansemannn I think the new API makes sense and I really like it.

**Comment by hansemannn** [comment]
@vijaysingh-axway `-34018` indicates invalid entitlements. Please ensure to use a provisioning profile that has the `Keychain Access` entitlement enabled in the iOS developer portal. We can check it out tomorrow together. Check [this page](https://www.osstatus.com/search/results?platform=all&framework=all&search=34018), I used it like a trillion times during development.

Will address the rest of the comments today!

**Pull request merged**
